name: Build and Deploy

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Use Node.js 12.x
      uses: actions/setup-node@v1
      with:
        node-version: '12.x'
    - name: npm install, test, and build
      run: |
        npm ci
        npm run lint
        npm test
        npm run build
      env:
        CI: true
        name: CI
    - name: Deploy the build
      uses: contention/rsync-deployments@v1.0.0
      env:
        DEPLOY_KEY: ${{ secrets.DECIDEL_SERVER_SSH_KEY }}
        ARGS: "-a"
        SERVER_PORT: ${{ secrets.DECIDEL_SERVER_PORT }}
        FOLDER: "build/"
        SERVER_IP: ${{ secrets.DECIDEL_SERVER_IP }}
        USERNAME: ${{ secrets.DECIDEL_SERVER_USERNAME }}
        SERVER_DESTINATION: ${{ secrets.DECIDEL_SERVER_WEB_DESTINATION }}
